unidad3/Proyecto Final/InventarioFerreteria/InventarioFerreteria/Models/Compra.cs
using System.ComponentModel.DataAnnotations;

namespace InventarioFerreteria.Models
{
    public class Compra
    {
        public int ComprasId { get; set; }

        [Display(Name = "Producto")]
        [Required(ErrorMessage = "El {0} del producto es requerido")]
        public int ProductoId { get; set; }

        [Required(ErrorMessage = "La {0} es requerida")]
        [Range(1, int.MaxValue, ErrorMessage = "La {0} debe ser un número positivo")]
        public int Cantidad { get; set; }

        [StringLength(1000, ErrorMessage = "La {0} debe tener como máximo {1} caracteres")]
        public string Descripcion { get; set; }

        [Display(Name = "Proveedor")]
        [Required(ErrorMessage = "El {0} del es requerido")]
        public int ProveedorId { get; set; }

        [Required(ErrorMessage = "La {0} es requerida")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }

        public Compra compra { get; set; }
        public string ProductoNombre { get; set; }
        public string ProveedorNombre { get; set; }
        
    }
}

unidad3/Proyecto Final/InventarioFerreteria/InventarioFerreteria/Models/CompraViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InventarioFerreteria.Models
{
    public class CompraViewModel : Compra
    {
        public IEnumerable<SelectListItem> Productos { get; set; }
        public IEnumerable<SelectListItem> Proveedores { get; set; }
    }
}

unidad3/Proyecto Final/InventarioFerreteria/InventarioFerreteria/Models/Compras.cs
namespace InventarioFerreteria.Models
{
    public class Compras
    {
        public int ComprasId { get; set; }
        public int ProductoId { get; set; }
        public int Cantidad { get; set; }
        public string Descripcion { get; set; }
        public int ProveedorId { get; set; }
        public DateTime Fecha { get; set; }
    }
}

unidad3/Proyecto Final/InventarioFerreteria/InventarioFerreteria/Controllers/CompraController.cs
using InventarioFerreteria.Models;
using InventarioFerreteria.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InventarioFerreteria.Controllers
{
    public class CompraController : Controller
    {
        private readonly IRepositorioCompra repositorioCompra;
        private readonly IRepositorioProductos repositorioProductos;
        private readonly IRepositorioProveedor repositorioProveedor;

        public CompraController(IRepositorioCompra repositorioCompra,
            IRepositorioProductos repositorioProductos,
            IRepositorioProveedor repositorioProveedor)
        {
            this.repositorioCompra = repositorioCompra;
            this.repositorioProductos = repositorioProductos;
            this.repositorioProveedor = repositorioProveedor;
        }

        public async Task<IActionResult> Index()
        {
            var compras = await repositorioCompra.ObtenerCompras();
            return View(compras);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            var proveedores = await repositorioProveedor.ObtenerProveedores();
            var productos = await repositorioProductos.Obtener();

            var proveedoresListItem = proveedores.Select
            (proveedor => new SelectListItem(proveedor.Nombre, proveedor.ProveedorId.ToString()));
            var productosListItem = productos.Select
            (producto => new SelectListItem(producto.Nombre, producto.ProductoId.ToString()));

            var obtenerCompra = new CompraViewModel
            {
                Proveedores = proveedoresListItem,
                Productos = productosListItem
            };

            return View(obtenerCompra);
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Compra compra)
        {
            if (!ModelState.IsValid)
            {
                return View(compra);
            }

            var compraDb = await repositorioCompra.Crear(compra);

            return RedirectToAction("Index");
        }
    }
}

unidad3/Proyecto Final/InventarioFerreteria/InventarioFerreteria/Views/Compra/Crear.cshtml
@model CompraViewModel

@{
    ViewData["Title"] = "Ingresar una nueva compra";
}

<h1>@ViewData["Title"]</h1>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-controller="Compra" asp-action="Crear" class="form-edit">
    <div class="mb-3 form-group">
        <label class="form-label" asp-for="compra.Fecha"></label>
        <input asp-for="compra.Fecha" class="form-control" placeholder="Fecha" type="datetime-local" />
        <span asp-validation-for="compra.Fecha" class="text-danger"></span>
    </div>

    <div class="mb-3 form-group">
        <label class="form-label" asp-for="compra.Descripcion"></label>
        <input asp-for="compra.Descripcion" class="form-control" placeholder="Descripcion" />
        <span asp-validation-for="compra.Descripcion" class="text-danger"></span>
    </div>

    <div class="mb-3 form-group">
        <label class="form-label" asp-for="compra.Cantidad"></label>
        <input asp-for="compra.Cantidad" class="form-control" placeholder="Cantidad" />
        <span asp-validation-for="compra.Cantidad" class="text-danger"></span>
    </div>

    <div class="mb-3 form-group">
        <label for="producto">Productos:</label>
        <select class="form-control" id="producto" asp-for="compra.ProductoId" asp-items="Model.Productos">
        </select>
    </div>

    <div class="mb-3 form-group">
        <label for="proveedor">Proveedor:</label>
        <select class="form-control" id="proveedor" asp-for="compra.ProveedorId" asp-items="Model.Proveedores">
        </select>
    </div>

    <button class="btn btn-primary" type="submit">Guardar</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

unidad3/Proyecto Final/InventarioFerreteria/InventarioFerreteria/Views/Compra/Index.cshtml
@model IEnumerable<Compra>

@{
    ViewData["Title"] = "Listado de compras";
}

<h1>@ViewData["Title"]</h1>

<div class="mb-3 mt-3">
    <a asp-action="Crear" class="btn btn-dark"><i class="bi bi-cart4"></i> Nueva Compra</a>
</div>

<table class="table tablas">
    <thead>
        <tr>
            <th>Producto</th>
            <th>Fecha</th>
            <th>Descripcion</th>
            <th>Cantidad</th>
            <th>Proveedor</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var compra in Model)
        {
            <tr>
                <th>@compra.ProductoNombre</th>
                <td>@compra.Fecha</td>
                <td>@compra.Descripcion</td>
                <td>@compra.Cantidad</td>
                <th>@compra.ProveedorNombre</th>
            </tr>
        }
    </tbody>
</table>